version: "3"
services:

  frontend:
    image: "node"
    volumes:
      - "./:/var/www/html"
    working_dir: "/var/www/html"
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run dev"

# Network.
networks:
  app:
    driver: bridge

volumes:
  appdb:
    driver: local
  appredis:
    driver: local
